### ISSUE TITLE
New error message when I'm using yahoofinancer

### ISSUE THREAD

**Issue by FV83** [rsquaredacademy/yahoofinancer#7]
Hello,
I am a regular user of the R package yahoofinancer. The last time I used it, in May, it worked perfecty.

But now in October, I had this issue:

y <- Ticker$new("GOOG")
y.yearly <- y$get_income_statement('annual')
Yahoo Finance API request failed
Status: 401
Type: Client error
Mesage:
Descript

Then, I updated the R package 'yahoofinancer' from github and I now get this message:
> y <- Ticker$new("GOOG")
> y.yearly <- y$get_income_statement('annual')
**Error: attempt to apply non-function**

Would it be possible that the get_income_statement() function does not work anymore because of changes in the yahoo API features?

Thanks a lot.

**Comment by aravindhebbali** [comment]
Hello @FV83,

There have been a lot of changes to the Yahoo Finance API since May. Only a subset of the original data is available now. You can look at the list of data available [here](https://yahoofinancer.rsquaredacademy.com/reference/).
